import type { RasterAdjustment } from "@vravio/env-raster";
import { Checkbox } from "../ui/atoms/Checkbox";
import { SliderWithNumber } from "../ui/molecules/SliderWithNumber";
import { builtInLuts, parseCubeLut } from "@vravio/env-raster";
import { localized, text } from "../i18n";
import { diagnostic } from "../diagnostics";
import type { AdjustmentEditorProps } from "./types";

/**
 * The adjustment dialogs' slider row, now the shared molecule underneath.
 *
 * The name and props are kept so the thirty-odd call sites below do not
 * change, but the two hand-rolled inputs this used to render are gone: the
 * options bar and these dialogs had grown separate implementations of the
 * same row, and the one that stayed is the one with the wheel, the scrubby
 * drag, modifier-scaled steps and Escape.
 */
function NumberSlider({ label, value, min, max, step = 1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange(value: number): void }) {
  return <SliderWithNumber className="adjustment-field" label={label} value={value} spec={{ min, max, step }} onChange={onChange} />;
}

function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange(value: boolean): void }) { return <Checkbox className="adjustment-check" label={label} checked={checked} onChange={onChange} />; }

function Histogram({ values }: { values?: readonly number[] | undefined }) {
  const bins = values?.length ? values : Array.from({ length: 64 }, (_, index) => Math.sin(index / 63 * Math.PI) ** 2);
  const max = Math.max(1, ...bins);
  const points = bins.map((value, index) => `${index / Math.max(1, bins.length - 1) * 100},${40 - value / max * 38}`).join(" ");
  return <svg className="adjustment-histogram" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="Histogram (Гистограмма)"><polygon points={`0,40 ${points} 100,40`}/></svg>;
}

function CurveEditor({ adjustment, change, histogram }: { adjustment: Extract<RasterAdjustment, { kind: "curves" }>; change(value: RasterAdjustment): void; histogram?: readonly number[] | undefined }) {
  const points = [...adjustment.points].sort((a, b) => a.x - b.x);
  const path = points.map((point, index) => `${index ? "L" : "M"}${point.x} ${255 - point.y}`).join(" ");
  const move = (index: number, axis: "x" | "y", value: number) => {
    const next = points.map((point, pointIndex) => pointIndex === index ? { ...point, [axis]: Math.max(0, Math.min(255, value)) } : point);
    change({ kind: "curves", points: next });
  };
  return <div className="curve-editor"><div className="curve-graph"><Histogram values={histogram}/><svg viewBox="0 0 255 255" preserveAspectRatio="none"><path d="M0 255L255 0" className="curve-baseline"/><path d={path} className="curve-line"/>{points.map((point, index) => <circle key={`${point.x}-${point.y}-${index}`} cx={point.x} cy={255 - point.y} r="4"/>)}</svg></div><div className="curve-points">{points.map((point, index) => <div key={index}><input aria-label="Input" type="number" min="0" max="255" value={point.x} onChange={(event) => move(index, "x", event.target.valueAsNumber)}/><input aria-label="Output" type="number" min="0" max="255" value={point.y} onChange={(event) => move(index, "y", event.target.valueAsNumber)}/>{index > 0 && index < points.length - 1 && <button onClick={() => change({ kind: "curves", points: points.filter((_, pointIndex) => pointIndex !== index) })}>−</button>}</div>)}<button onClick={() => change({ kind: "curves", points: [...points, { x: 128, y: 128 }].sort((a, b) => a.x - b.x) })}>＋</button></div></div>;
}

export function AdjustmentEditor({ value, language, histogram, onChange }: AdjustmentEditorProps) {
  const patch = (next: Record<string, unknown>) => onChange({ ...value, ...next } as RasterAdjustment);
  if (value.kind === "invert") return <p className="panel-hint">{text(language, "No parameters", "Нет параметров")}</p>;
  if (value.kind === "brightnessContrast") return <><NumberSlider label={text(language, "Brightness", "Яркость")} value={value.brightness} min={-100} max={100} onChange={(brightness) => patch({ brightness })}/><NumberSlider label={text(language, "Contrast", "Контрастность")} value={value.contrast} min={-100} max={100} onChange={(contrast) => patch({ contrast })}/></>;
  if (value.kind === "exposure") return <><NumberSlider label={text(language, "Exposure", "Экспозиция")} value={value.exposure} min={-20} max={20} step={.01} onChange={(exposure) => patch({ exposure })}/><NumberSlider label={text(language, "Offset", "Сдвиг")} value={value.offset} min={-.5} max={.5} step={.001} onChange={(offset) => patch({ offset })}/><NumberSlider label={text(language, "Gamma correction", "Гамма-коррекция")} value={value.gamma} min={.01} max={9.99} step={.01} onChange={(gamma) => patch({ gamma })}/></>;
  if (value.kind === "vibrance") return <><NumberSlider label={text(language, "Vibrance", "Красочность")} value={value.vibrance} min={-100} max={100} onChange={(vibrance) => patch({ vibrance })}/><NumberSlider label={text(language, "Saturation", "Насыщенность")} value={value.saturation} min={-100} max={100} onChange={(saturation) => patch({ saturation })}/></>;
  if (value.kind === "levels") return <><label className="adjustment-channel">{text(language, "Channel", "Канал")}<select><option>RGB</option></select></label><Histogram values={histogram}/><NumberSlider label={text(language, "Input black", "Вход: чёрная точка")} value={value.blackInput} min={0} max={254} onChange={(blackInput) => patch({ blackInput })}/><NumberSlider label={text(language, "Gamma", "Гамма")} value={value.gamma} min={.1} max={10} step={.01} onChange={(gamma) => patch({ gamma })}/><NumberSlider label={text(language, "Input white", "Вход: белая точка")} value={value.whiteInput} min={1} max={255} onChange={(whiteInput) => patch({ whiteInput })}/><NumberSlider label={text(language, "Output black", "Выход: чёрная точка")} value={value.blackOutput} min={0} max={254} onChange={(blackOutput) => patch({ blackOutput })}/><NumberSlider label={text(language, "Output white", "Выход: белая точка")} value={value.whiteOutput} min={1} max={255} onChange={(whiteOutput) => patch({ whiteOutput })}/></>;
  if (value.kind === "curves") return <CurveEditor adjustment={value} change={onChange} histogram={histogram}/>;
  if (value.kind === "hueSaturation") return <><NumberSlider label={text(language, "Hue", "Цветовой тон")} value={value.hue} min={-180} max={180} onChange={(hue) => patch({ hue })}/><NumberSlider label={text(language, "Saturation", "Насыщенность")} value={value.saturation} min={-100} max={100} onChange={(saturation) => patch({ saturation })}/><NumberSlider label={text(language, "Lightness", "Яркость")} value={value.lightness} min={-100} max={100} onChange={(lightness) => patch({ lightness })}/></>;
  if (value.kind === "colorBalance") return <><NumberSlider label={text(language, "Cyan / Red", "Голубой / Красный")} value={value.cyanRed} min={-100} max={100} onChange={(cyanRed) => patch({ cyanRed })}/><NumberSlider label={text(language, "Magenta / Green", "Пурпурный / Зелёный")} value={value.magentaGreen} min={-100} max={100} onChange={(magentaGreen) => patch({ magentaGreen })}/><NumberSlider label={text(language, "Yellow / Blue", "Жёлтый / Синий")} value={value.yellowBlue} min={-100} max={100} onChange={(yellowBlue) => patch({ yellowBlue })}/></>;
  if (value.kind === "blackWhite") return <>{(["reds", "yellows", "greens", "cyans", "blues", "magentas"] as const).map((key) => <NumberSlider key={key} label={text(language, key[0]!.toUpperCase() + key.slice(1), ({ reds: "Красные", yellows: "Жёлтые", greens: "Зелёные", cyans: "Голубые", blues: "Синие", magentas: "Пурпурные" } as const)[key])} value={value[key]} min={-200} max={300} onChange={(amount) => patch({ [key]: amount })}/>)}<Check label={text(language, "Tint", "Оттенок")} checked={value.tint} onChange={(tint) => patch({ tint })}/>{value.tint && <label className="adjustment-color">{text(language, "Tint color", "Цвет оттенка")}<input type="color" value={value.tintColor} onChange={(event) => patch({ tintColor: event.target.value })}/></label>}</>;
  if (value.kind === "photoFilter") return <><label className="adjustment-color">{text(language, "Filter color", "Цвет фильтра")}<input type="color" value={value.color} onChange={(event) => patch({ color: event.target.value })}/></label><NumberSlider label={text(language, "Density", "Плотность")} value={value.density} min={0} max={100} onChange={(density) => patch({ density })}/><Check label={text(language, "Preserve luminosity", "Сохранить свечение")} checked={value.preserveLuminosity} onChange={(preserveLuminosity) => patch({ preserveLuminosity })}/></>;
  if (value.kind === "channelMixer") { const channel = value.outputChannel, weights = value[channel]; const labels = [text(language, "Red", "Красный"), text(language, "Green", "Зелёный"), text(language, "Blue", "Синий"), text(language, "Constant", "Постоянный")]; return <><label className="adjustment-channel">{text(language, "Output channel", "Целевой канал")}<select value={channel} onChange={(event) => patch({ outputChannel: event.target.value })}><option value="red">{text(language, "Red", "Красный")}</option><option value="green">{text(language, "Green", "Зелёный")}</option><option value="blue">{text(language, "Blue", "Синий")}</option></select></label><Check label={text(language, "Monochrome", "Монохромный")} checked={value.monochrome} onChange={(monochrome) => patch({ monochrome })}/>{weights.map((amount, index) => <NumberSlider key={labels[index]} label={labels[index]!} value={amount} min={-200} max={200} onChange={(next) => { const row = [...weights] as [number, number, number, number]; row[index] = next; patch({ [channel]: row }); }}/>)}</> }
  if (value.kind === "gradientMap") return <><div className="gradient-map-preview" style={{ background: `linear-gradient(90deg, ${value.reverse ? value.to : value.from}, ${value.reverse ? value.from : value.to})` }}/><div className="gradient-colors"><input type="color" value={value.from} onChange={(event) => patch({ from: event.target.value })}/><input type="color" value={value.to} onChange={(event) => patch({ to: event.target.value })}/></div><Check label={text(language, "Dither", "Дизеринг")} checked={value.dither} onChange={(dither) => patch({ dither })}/><Check label={text(language, "Reverse", "Инверсия")} checked={value.reverse} onChange={(reverse) => patch({ reverse })}/></>;
  if (value.kind === "selectiveColor") { const selected = value.values[value.range], update = (key: "cyan" | "magenta" | "yellow" | "black", amount: number) => patch({ values: { ...value.values, [value.range]: { ...selected, [key]: amount } } }); return <><label className="adjustment-channel">{text(language, "Colors", "Цвета")}<select value={value.range} onChange={(event) => patch({ range: event.target.value })}>{(["reds", "yellows", "greens", "cyans", "blues", "magentas", "whites", "neutrals", "blacks"] as const).map((range) => <option key={range} value={range}>{range}</option>)}</select></label><NumberSlider label={text(language, "Cyan", "Голубой")} value={selected.cyan} min={-100} max={100} onChange={(amount) => update("cyan", amount)}/><NumberSlider label={text(language, "Magenta", "Пурпурный")} value={selected.magenta} min={-100} max={100} onChange={(amount) => update("magenta", amount)}/><NumberSlider label={text(language, "Yellow", "Жёлтый")} value={selected.yellow} min={-100} max={100} onChange={(amount) => update("yellow", amount)}/><NumberSlider label={text(language, "Black", "Чёрный")} value={selected.black} min={-100} max={100} onChange={(amount) => update("black", amount)}/><label className="adjustment-method"><input type="radio" checked={value.method === "relative"} onChange={() => patch({ method: "relative" })}/>{text(language, "Relative", "Относительная")}</label><label className="adjustment-method"><input type="radio" checked={value.method === "absolute"} onChange={() => patch({ method: "absolute" })}/>{text(language, "Absolute", "Абсолютная")}</label></> }
  if (value.kind === "shadowsHighlights") return <><NumberSlider label={text(language, "Shadows", "Тени")} value={value.shadows} min={0} max={100} onChange={(shadows) => patch({ shadows })}/><NumberSlider label={text(language, "Highlights", "Света")} value={value.highlights} min={0} max={100} onChange={(highlights) => patch({ highlights })}/><details><summary>{text(language, "Show more options", "Показать дополнительные параметры")}</summary><NumberSlider label={text(language, "Color correction", "Коррекция цвета")} value={value.colorCorrection} min={-100} max={100} onChange={(colorCorrection) => patch({ colorCorrection })}/><NumberSlider label={text(language, "Midtone contrast", "Контраст средних тонов")} value={value.midtoneContrast} min={-100} max={100} onChange={(midtoneContrast) => patch({ midtoneContrast })}/><NumberSlider label={text(language, "Black clip", "Отсечение чёрного")} value={value.blackClip} min={0} max={50} step={.01} onChange={(blackClip) => patch({ blackClip })}/><NumberSlider label={text(language, "White clip", "Отсечение белого")} value={value.whiteClip} min={0} max={50} step={.01} onChange={(whiteClip) => patch({ whiteClip })}/></details></>;
  if (value.kind === "posterize") return <NumberSlider label={text(language, "Levels", "Уровни")} value={value.levels} min={2} max={255} onChange={(levels) => patch({ levels })}/>;
  if (value.kind === "threshold") return <><Histogram values={histogram}/><NumberSlider label={text(language, "Threshold", "Порог")} value={value.threshold} min={0} max={255} onChange={(threshold) => patch({ threshold })}/></>;
  return <><label className="adjustment-channel">{text(language, "Look", "Профиль")}<select value={value.lut.title} onChange={(event) => { const lut = builtInLuts.find((item) => item.title === event.target.value); if (lut) patch({ lut }); }}>{[value.lut, ...builtInLuts.filter((item) => item.title !== value.lut.title)].map((item) => <option key={item.title} value={item.title}>{localized(item.title, language)}</option>)}</select></label><NumberSlider label={text(language, "Amount", "Сила")} value={Math.round(value.amount * 100)} min={0} max={100} onChange={(amount) => patch({ amount: amount / 100 })}/><label className="lut-load">{text(language, "Load .cube", "Загрузить .cube")}<input type="file" accept=".cube,text/plain" onChange={(event) => { const file = event.target.files?.[0]; event.currentTarget.value = ""; if (!file) return; void file.text().then((content) => patch({ lut: parseCubeLut(content, file.name.replace(/\.cube$/i, "")) })).catch((error) => diagnostic("error", "lut.parse", error instanceof Error ? error.message : String(error), { file: file.name })); }}/></label></>;
}
